#!/usr/bin/env bash
# script that transfers a file from our client to a server:
# Accepts 4 parameters
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp connects with
# The path to the SSH private key that scp uses
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# if less than 3 parameters passed
FILEPATH=$1
IP=$2
USERNAME=$3
SSHPrivateKey=$4
if [ "$#" -gt 3 ]; then
    scp -o StrictHostKeyChecking=no -i "$SSHPrivateKey" "$FILEPATH" "$USERNAME"@"$IP":~
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
