#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# configure web-02 to be identical to web-01.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chown -R "$USER:$USER" /var/www/html
echo "Holberton School" >> /var/www/html/index.html
echo "Ceci n'est pas une page" >> /var/www/html/custom_404.html
new="_;\n\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/_;/$new/" /etc/nginx/sites-available/default
sudo sed -i 's/http {/http {\n\n\tadd_header X-Served-By $hostname;/' /etc/nginx/nginx.conf
sudo service nginx start
sudo service nginx restart
