#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.
PW=$1
DT=$(date '+%d-%m-%Y')
mysqldump --user=root --password="$PW" --lock-tables --all-databases > backup.sql
tar -czvf "$DT".tar.gz backup.sql
