#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.
# With a sleep 2 in between each iteration
# displays I am invincible!!! when receiving a SIGTERM signal
i=0
while [ $i -lt 1 ]
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo I am invincible!!!" SIGTERM
    i=$(( i-1 ))
done
