#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
file=/etc/passwd
while IFS=: read -r USERNAME PASSWORD USER_ID gid desc HOME_DIRECTORY SHELL
do
    echo "The user $USERNAME is part of the $gid gang, lives in $HOME_DIRECTORY and rides $SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $desc"
done < "$file"
