#!/usr/bin/env bash
# Write a Bash script that displays Holberton School 10 times,
#but for the 9th iteration, displays Holberton School
#and then Hi on a new line.
i=0
while [ $i -lt 10 ]
do
	if [ $i != 8 ];
		then
			echo "Holberton School"
		else
			echo "Holberton School"
			echo "Hi"
	fi
	i=$(( i+1 ))
done
