#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
i=1
while [ $i -lt 21 ]
do
	case $i in
    	[0-3]|10)	echo $i
        ;;
        [4]) echo $i
             echo "bad luck form China"
        ;;
        [5-8]) echo $i
        ;;
        [9]) echo $i
             echo "bad luck from Japan"
        ;;
        1[0-6]|20) echo $i
        ;;
        1[7]) echo $i
              echo "bad luck from Italy"
        ;;
        1[8-9]) echo $i
        ;;
        esac
	i=$(( i+1 ))
done
