#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
h=0
while [ $h -lt 13 ]
do
    m=1
	while [ $m -lt 60 ];
    do
        if [ $m -eq 1 ]
            then
                echo "Hour: "$h
                echo $m
		else
            echo $m
        fi
        m=$(( m+1 ))
    done
	h=$(( h+1 ))
done
